[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

# Add headers for CSS and other static assets
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"